=== openplanets/droid/droid-results/src/test/resources/droidDbUnit.dtd
<!ELEMENT dataset (
    FORMAT*,
    HIBERNATE_UNIQUE_KEY*,
    IDENTIFICATION*,
    PROFILE_RESOURCE_NODE*)>

<!ELEMENT FORMAT EMPTY>
<!ATTLIST FORMAT
    PUID CDATA #REQUIRED
    MIME_TYPE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    VERSION CDATA #IMPLIED
>

<!ELEMENT HIBERNATE_UNIQUE_KEY EMPTY>
<!ATTLIST HIBERNATE_UNIQUE_KEY
    NEXT_HI CDATA #IMPLIED
>

<!ELEMENT IDENTIFICATION EMPTY>
<!ATTLIST IDENTIFICATION
    NODE_ID CDATA #REQUIRED
    PUID CDATA #REQUIRED
>

<!ELEMENT PROFILE_RESOURCE_NODE EMPTY>
<!ATTLIST PROFILE_RESOURCE_NODE
    NODE_ID CDATA #REQUIRED
    EXTENSION_MISMATCH CDATA #REQUIRED
    IDENTIFICATION_COUNT CDATA #IMPLIED
    EXTENSION CDATA #IMPLIED
    HASH CDATA #IMPLIED
    IDENTIFICATION_METHOD CDATA #IMPLIED
    LAST_MODIFIED_DATE CDATA #IMPLIED
    NAME CDATA #REQUIRED
    NODE_STATUS CDATA #IMPLIED
    RESOURCE_TYPE CDATA #REQUIRED
    FILE_SIZE CDATA #IMPLIED
    PREFIX CDATA #IMPLIED
    PREFIX_PLUS_ONE CDATA #IMPLIED
    TEXT_ENCODING CDATA #IMPLIED
    URI CDATA #REQUIRED
    PARENT_ID CDATA #IMPLIED
>

=== openplanets/droid/droid-results/src/test/resources/uk/gov/nationalarchives/droid/planet/xml/dao/planets-xml-test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../../../../../../../droidDbUnit.dtd">

<dataset> 
   <FORMAT PUID="fmt/richard"/>
   <FORMAT PUID="fmt/matt"/>
   <FORMAT PUID="fmt/alok"/>
   <FORMAT PUID="NONE"/>

   <PROFILE_RESOURCE_NODE URI="file:/dir1/"           NAME="dir1" LAST_MODIFIED_DATE="2009-01-01 12:00:00"	NODE_ID="1"   RESOURCE_TYPE="0" PREFIX="AA" PREFIX_PLUS_ONE="AB"  EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/unreadable/"     NAME="unreadable" LAST_MODIFIED_DATE="2009-01-01 12:00:00"  NODE_ID="2"   RESOURCE_TYPE="0" PREFIX="AA" PREFIX_PLUS_ONE="AB" EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/dir1/file1.exe"  NODE_STATUS="1" LAST_MODIFIED_DATE="2010-01-01 12:00:00"	NODE_ID="11"  NAME="file1.exe" FILE_SIZE="256"  PARENT_ID="1" RESOURCE_TYPE="2" EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/dir1/file2.doc"  NODE_STATUS="1" LAST_MODIFIED_DATE="2010-01-01 12:00:00"	NODE_ID="12"  EXTENSION = "doc"  NAME="file2.doc" FILE_SIZE="256"  PARENT_ID="1" RESOURCE_TYPE="2" EXTENSION_MISMATCH="0"/>

   <PROFILE_RESOURCE_NODE URI="file:/dir1/file4.droid" NODE_STATUS="1" LAST_MODIFIED_DATE="2008-01-01 12:00:00"  NODE_ID="14"	NAME="file4.droid" FILE_SIZE="230"  PARENT_ID="1" RESOURCE_TYPE="1" EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/dir1/file5.txt"   NODE_STATUS="1" LAST_MODIFIED_DATE="2007-01-01 12:00:00"  NODE_ID="15"	NAME="file5.txt" FILE_SIZE="4000" PARENT_ID="1" RESOURCE_TYPE="2" EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/dir1/file6.doc"   NODE_STATUS="1" LAST_MODIFIED_DATE="2007-01-01 12:00:00"   NODE_ID="16"	NAME="file6.doc" FILE_SIZE="8000" PARENT_ID="1" RESOURCE_TYPE="2"  EXTENSION_MISMATCH="0"/>
   <PROFILE_RESOURCE_NODE URI="file:/dir1/file3.xls"   NODE_STATUS="3" LAST_MODIFIED_DATE="2008-01-01 12:00:00"  NODE_ID="13"	NAME="file3.xls" FILE_SIZE="140"   PARENT_ID="1" RESOURCE_TYPE="2" EXTENSION_MISMATCH="0"/>   

   <IDENTIFICATION NODE_ID="14" PUID="fmt/richard"/>
   <IDENTIFICATION NODE_ID="13" PUID="fmt/richard"/>   
   <IDENTIFICATION NODE_ID="15" PUID="fmt/matt"/>
   <IDENTIFICATION NODE_ID="16" PUID="fmt/matt"/>
   
   <IDENTIFICATION NODE_ID="1" PUID="NONE"/>
   <IDENTIFICATION NODE_ID="11" PUID="fmt/alok"/>
   <IDENTIFICATION NODE_ID="12" PUID="fmt/alok"/>
   
</dataset>

=== openplanets/droid/droid-results/src/test/resources/uk/gov/nationalarchives/droid/profile/results-test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "../../../../../droidDbUnit.dtd">

<dataset> 
   <FORMAT PUID="fmt/alok"/>
   <FORMAT PUID="NONE"/>

   <PROFILE_RESOURCE_NODE NODE_ID="1"  EXTENSION_MISMATCH="0" NAME="dir1"  RESOURCE_TYPE="2" PREFIX="AA" PREFIX_PLUS_ONE="AB" URI="file:/dir1/"/>
   <PROFILE_RESOURCE_NODE NODE_ID="11" EXTENSION_MISMATCH="0" EXTENSION="exe" NAME="file1.exe" NODE_STATUS="1" RESOURCE_TYPE="1" FILE_SIZE="256" PREFIX="AAA" PREFIX_PLUS_ONE="AAB" URI="file:/dir1/file1.exe" PARENT_ID="1"/>
   <PROFILE_RESOURCE_NODE NODE_ID="12" EXTENSION_MISMATCH="0" EXTENSION="doc" NAME="file2.doc" NODE_STATUS="1" RESOURCE_TYPE="1" FILE_SIZE="256" PREFIX="AAB" PREFIX_PLUS_ONE="AAC" URI="file:/dir1/file2.doc" PARENT_ID="1"/>
   
   
   <IDENTIFICATION NODE_ID="11" PUID="fmt/alok"/>
   <IDENTIFICATION NODE_ID="12" PUID="fmt/alok"/>
   <IDENTIFICATION NODE_ID="1" PUID="NONE"/>
</dataset>
