=== openplanets/droid/droid-report/src/main/resources/xsd/droidFilterSpecification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.nationalarchives.gov.uk/pronom/droidFilterSpecification"
	 elementFormDefault="unqualified" 
	 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.nationalarchives.gov.uk/pronom/droidFilterSpecification">
 
    <xsd:annotation>
    	<xsd:documentation>This schema defines the form of filters used in the DROID application.  Filters can be applied to profiles, and additionally to report summaries.</xsd:documentation>
    </xsd:annotation>

    <xsd:element name="filter" type="filterSpecificationType"></xsd:element>

    <xsd:complexType name="filterSpecificationType">
    	<xsd:sequence>
    		<xsd:element name="enabled" type="xsd:boolean" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="combinationMethod" type="criteriaConditionEnum" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="criteria" type="filterCriterionListType" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
   
    <xsd:simpleType name="criteriaConditionEnum">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="allCriterionAreMet"></xsd:enumeration>
    		<xsd:enumeration value="anyCriterionAreMet"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="filterCriterionType">
    	<xsd:sequence>
    		<xsd:element name="fieldName" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="operator" type="operatorEnum" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="valueFreeText" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="selectedValues" type="selectedValueListType" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="rowNumber" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="operatorEnum">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="equals"></xsd:enumeration>
    		<xsd:enumeration value="is not"></xsd:enumeration>
    		<xsd:enumeration value="less than"></xsd:enumeration>
    		<xsd:enumeration value="greater than"></xsd:enumeration>
    		<xsd:enumeration value="less or equals"></xsd:enumeration>
    		<xsd:enumeration value="greater or equals"></xsd:enumeration>
    		<xsd:enumeration value="begins with"></xsd:enumeration>
    		<xsd:enumeration value="ends with"></xsd:enumeration>
    		<xsd:enumeration value="contains"></xsd:enumeration>
    		<xsd:enumeration value="any of"></xsd:enumeration>
    		<xsd:enumeration value="none of"></xsd:enumeration>
    		<xsd:enumeration value="has duplicates"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="selectedValueType">
    	<xsd:sequence>
    		<xsd:element name="id" type="xsd:int" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="queryParameter" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="selectedValueListType">
    	<xsd:sequence>
    		<xsd:element name="selectedValue" type="selectedValueType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="filterCriterionListType">
    	<xsd:sequence>
    		<xsd:element name="criterion" type="filterCriterionType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== openplanets/droid/droid-report/src/test/resources/exampleFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<filterSpec:filter xmlns:filterSpec="http://www.nationalarchives.gov.uk/pronom/droidFilterSpecification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nationalarchives.gov.uk/pronom/droidFilterSpecification droidFilterSpecification.xsd ">
  <enabled>true</enabled>
  <combinationMethod>allCriterionAreMet</combinationMethod>
  <criteria>
    <criterion>
      <fieldName>fieldName</fieldName>
      <operator>equals</operator>
      <valueFreeText>valueFreeText</valueFreeText>
      <selectedValues>
        <selectedValue>
          <id>0</id>
          <description>description</description>
          <queryParameter>queryParameter</queryParameter>
        </selectedValue>
      </selectedValues>
      <rowNumber>0</rowNumber>
    </criterion>
  </criteria>
</filterSpec:filter>
